version: "3.9"
services:
  evolutionary-cpc2ccs:
    build: ../
    volumes:
      - ./cpc2ccs/:/app/output_dir/
      - ../../../ontologies/sub_ontologies/cpc2ccs/:/app/onto_dir/
  evolutionary-cpc2cso:
    build: ../
    depends_on:
      evolutionary-cpc2ccs:
        condition: service_completed_successfully
    volumes:
      - ./cpc2cso/:/app/output_dir/
      - ../../../ontologies/sub_ontologies/cpc2cso/:/app/onto_dir/
  evolutionary-anatomy:
    build: ../
    depends_on:
      evolutionary-cpc2cso:
        condition: service_completed_successfully
    volumes:
      - ./anatomy/:/app/output_dir/
      - ../../../ontologies/sub_ontologies/anatomy/:/app/onto_dir/
